// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrRIJVutDJ7LlBvsDgNE64hKAvEFyPHLI',
    appId: '1:827981671830:web:80f684277a3781c03981b7',
    messagingSenderId: '827981671830',
    projectId: 'shram-daan',
    authDomain: 'shram-daan.firebaseapp.com',
    storageBucket: 'shram-daan.firebasestorage.app',
    measurementId: 'G-ZWJJGB4KYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx8-2gcKU4JyBrrfJfUbW46D7pweu1qmc',
    appId: '1:827981671830:android:105445f027feb0083981b7',
    messagingSenderId: '827981671830',
    projectId: 'shram-daan',
    storageBucket: 'shram-daan.firebasestorage.app',
  );

}